# https://github.com/helm/charts/pull/7084#issuecomment-412018277

apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  volumes:
    - name: ssh-secrets
      secret:
        secretName: gocd-agent-ssh
  imagePullSecrets:
    - name: docker-registry
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v19.3.0
      securityContext:
        privileged: true
      volumeMounts: 
        - name: ssh-secrets
          readOnly: true
          mountPath: /home/go/.ssh