apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-awscli-{{ POD_POSTFIX }}
  labels:
    app: web

spec:
  serviceAccountName: default
  containers:
    - name: gocd-agent-container-awscli-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v19.3.0
      securityContext:
        privileged: true
      volumeMounts:
        - name: ssh-secrets
          readOnly: true
          mountPath: /home/go/.ssh
  volumes:
    - name: ssh-secrets
      secret:
      secretName: gocd-server-ssh
