install:

update:

test:

proxy:

status: 
	helm status gocd 
	
	# verificar existencia de:
	# 	secret gocd-server-ssh
	# 	secret docker-registry
	# no namespace:
	# 	gocd

delete:
	helm del --purge gocd