install:

proxy:
	# helm chart do kubernetes dashboard
	# port-forward

status: 
	echo "===== KUBERNETES : CLUSTER INFO DUMP"
	kubectl cluster-info dump

delete:
	echo "===== MINKUBE : DELETING"
	minikube delete